import Head from 'next/head'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import More from '../components/More'
import styles from '../styles/Home.module.css'
import { useRef } from 'react'
import Introduction from '../components/Introduction'
import Kassensystem from '../components/Kassensystem'
import Empfehlungen from '../components/Empfehlungen'

export default function Home() {
  const introRef = useRef()
  const kontaktRef = useRef()
  const kassenRef = useRef()
  const gastroRef = useRef()
  const blogRef = useRef()
  const empfehlungsRef = useRef()


  return (
    <div>
      <Head>
        <title>Das Multitalent für Ihre Gastronomie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <Hero scrollRef={introRef} />
          <More kassenRef={kassenRef} gastroRef={gastroRef} blogRef={blogRef} />
          <div ref={introRef}>
            <Introduction scrollRef={kontaktRef} />
          </div>
          <div ref={kassenRef}>
            <Kassensystem scrollRef={kontaktRef}/>
          </div>
          <div ref={blogRef} className='placeholder'>Blog</div>
          <div ref={empfehlungsRef}>
            <Empfehlungen/>
          </div>
          <div className='placeholder' ref={kontaktRef}>Kontakformular</div>
        </main>
      </Layout>
    </div>
  )
}
