import Head from 'next/head'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import More from '../components/More'
import styles from '../styles/Home.module.css'
import { useRef } from 'react'
import Introduction from '../components/Introduction'

export default function Home() {
  const introRef = useRef()

  return (
    <div>
      <Head>
        <title>Das Multitalent für Ihre Gastronomie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <Hero scrollRef={introRef} />
            <More />
          <div ref={introRef}>
            <Introduction/>
          </div>
        </main>
      </Layout>
    </div>
  )
}
